### ISSUE TITLE
mingw32-make is no longer required on Windows

### ISSUE THREAD

**Issue by WardBrian** [stan-dev/cmdstanr#1035]
**Describe the issue**
As of https://github.com/stan-dev/cmdstan/pull/1262, just plain old `make` can be used on Windows.

This code:
https://github.com/stan-dev/cmdstanr/blob/b762c54a752fab0bedc7951913186861b4706079/R/utils.R#L95-L101
Should either be updated or should at least check `$MAKE`

**Comment by jgabry** [comment]
So it sounds like I can just modify the function so the `if` clause also checks if the user has an older CmdStan installed, in which case we still need to use mingw32-make when we were using it before. So something like this: 

```r
 make_cmd <- function() { 
   if ((cmdstan_version() < "2.35.0") && os_is_windows() && !os_is_wsl() && (Sys.getenv("CMDSTANR_USE_RTOOLS") == "")) { 
     "mingw32-make.exe" 
   } else { 
     "make" 
   } 
 } 
```

where the only change is checking the version number too. If they have at least 2.35 then it just uses `make` for everyone, otherwise it does the same check as before. Does that seem right?

**Comment by WardBrian** [comment]
Seems fine, you may also want to check $MAKE regardless of system, and just fall back to these system-specific defaults if unset

**Comment by jgabry** [comment]
The reason my PR is failing is that `install_cmdstan` uses `make` _before_ `cmdstan_version()` can be checked (since it hasn't been installed yet). I guess we could use two different methods of choosing the `make` command, one to be used inside `install_cmdstan` and one to use elsewhere. The difference would be that in the former we check the version number from the release URL and in the latter we can use `cmdstan_version()`. Doable, but I don't love that idea. 

@WardBrian How are you dealing with this in CmdStanPy? Currently it looks like `install_cmdstan.py` still uses `mingw32-make` on Windows: https://github.com/stan-dev/cmdstanpy/blob/c5bcfb3164f18c68a6100dd9146721b68c34db80/cmdstanpy/install_cmdstan.py#L84

**Comment by WardBrian** [comment]
Well, it uses whatever `$MAKE` is set to, _or_ mingw32-make, which we still do install unconditionally. So in practice, things like cmdstan's conda recipe just make sure `$MAKE` is set, while the rest of the users are still going to be using mingw32-make for the time being. 

Eventually I'd like to introduce the idea of a "minimum supported cmdstan version" for a given version of cmdstanpy, and then drop all the conditionals stuff like this can lead to

**Comment by jgabry** [comment]
> Well, it uses whatever `$MAKE` is set to, _or_ mingw32-make, which we still do install unconditionally. So in practice, things like cmdstan's conda recipe just make sure `$MAKE` is set, while the rest of the users are still going to be using mingw32-make for the time being.

Oh ok, I see. I was thinking that since `make` is supported now that we'd want to fall back to just `make` (instead of `mingw32-make`) if `$MAKE` isn't set and CmdStan >=2.35.0. But I can just do the same thing you do in CmdStanPy and it should be fine. 

> Eventually I'd like to introduce the idea of a "minimum supported cmdstan version" for a given version of cmdstanpy, and then drop all the conditionals stuff like this can lead to

I agree, that would be nice.
