### ISSUE TITLE
Explore options for faster csv reading than utils::read.csv

### ISSUE THREAD

**Issue by jgabry** [stan-dev/cmdstanr#133]
At some point we should investigate if we can get a speedup by using other methods of reading in csv output. Currently we use the standard R function `utils::read.csv()`.

**Comment by mcol** [comment]
`data.table::fread` is massively faster for large files, and has an option to produce a `data.frame` if that's what you are looking for.

**Comment by rok-cesnovar** [comment]
Thanks! I will take a look at that.

**Comment by rok-cesnovar** [comment]
fread looks fast, but it doesn't support ignoring lines with "#". Most comments suggest using grep with fread to do that, which isn't really portable. They have an open issue to add this but its been longstanding.

[readr](https://readr.tidyverse.org/news/index.html ) is another option I looked into 

[vroom](https://www.tidyverse.org/blog/2020/01/vroom-1-1-0/) looks the most promising.
It has some issues with comments after the column names are specified:
```
lp__,accept_stat__,stepsize__,treedepth__,n_leapfrog__,divergent__,energy__,mu,sigma
# Adaptation terminated
# Step size = 0.672434
# Diagonal elements of inverse mass matrix:
# 0.909635, 0.066384
```
but that can be fixed in R afterwards:

For now I tried reading a csv with 41 params (sampler  + model params) with 90k iterations:
- utils::read.csv 2.46s
- readr 1.3s
- vroom 0.08s (they use lazy reading so not sure this is a totally fair comparison yet, but looks amazing)

```R
N <- 10
utils <- c()
for(i in 1:N) {
  t1 <- Sys.time()
  tmp1 <- utils::read.csv(csv_file, comment.char = "#", header = TRUE)
  t2 <- Sys.time()
  utils <- c(utils, (t2-t1))
}
print(paste0("utils::read.csv ", mean(utils)))

readr_times <- c()
for(i in 1:N) {
  t1 <- Sys.time()
  tmp2 <- readr::read_csv(csv_file, comment = "# ", trim_ws = TRUE)
  t2 <- Sys.time()
  readr_times <- c(readr_times, (t2-t1))
}
print(paste0("readr ", mean(readr_times)))

vroom_times <- c()
for(i in 1:N) {
  t1 <- Sys.time()
  tmp3 <- vroom::vroom(csv_file, comment = "# ", delim = ',', trim_ws = TRUE, col_types = c(lp__ = "d"))
  # fix the table
  tmp3 <- tmp3[!is.na(tmp3$lp__),]
  t2 <- Sys.time()
  vroom_times <- c(vroom_times, (t2-t1))
}
print(paste0("vroom ", mean(vroom_times)))
```

**Comment by rok-cesnovar** [comment]
I did a more thorough test and timed the entire read_sample_csv if we use utils, readr or vroom to read the file in.
readr and vroom both pass test-csv tests, apart that they dont throw on empty file, which is fine I think.

These are the benchmarks for the entire read_sample_csv function.

|       | 100MB | 50MB | 25MB | 12MB | 6MB  | 3MB  |
|-------|-------|------|------|------|------|------|
| utils | 10.45 | 4.51 | 2.43 | 1.24 | 0.60 | 0.27 |
| readr | 4.97  | 2.47 | 1.39 | 0.77 | 0.40 | 0.21 |
| vroom | 3.76  | 2.01 | 1.13 | 0.71 | 0.35 | 0.20 |

Both faster packages are GPL licensed tho, I am not sure if that makes them unusable? They also obviously bring in additional dependencies.
One additional benefit of vroom is that it can read in specific columns only if requested.

Anyhow, @jgabry I would like your feedback before I proceed.

**Comment by jgabry** [comment]
@rok-cesnovar I know we talked about this during our call last week, but just to have it documented here (and sorry for the delay): 

I think vroom looks good and I think it's fine to include it as a dependency even though it is GPL-3 and we are BSD-3. We can't ship any of the vroom source code with cmdstanr, but we can call vroom functions in cmdstanr.
