### ISSUE TITLE
Small wishlist for supporting cmdstanr in brms

### ISSUE THREAD

**Issue by paul-buerkner** [stan-dev/cmdstanr#173]
cmdstanr is already supported on a branch of brms (https://github.com/paul-buerkner/brms/pull/900) and mostly functional. I have some small things which I haven't seen how to do currently in cmdstanr.

- [ ] Is there a way to selectively include / exclude stored parameters as done with arguments `pars` and `include` in `rstan::sampling`? I know this would be done manually by editing the csv but I would prefer an option that does not require reading in the full csv first before selection. Not sure if this is a reasonable wish as I don't know if cmdstan itself has the option to not write certain parameters to csv in the first place.
- [ ] `rstan::sampling` has the option to turn off informational messages via `show_messages`. I could probably suppress all messages from cmdstanr from the outside but it might be better to only selectively suppress those Informational messages written during sampling.

**Comment by rok-cesnovar** [comment]
1. may be solved by https://github.com/stan-dev/cmdstanr/pull/164 which will also make reading in the CSV files much faster. The use will be `fit$draws(parameters= c("mu", "sigma"))` This will read only the selected parameters in memory (via the vroom package). But I am not sure that helps you since I think you said you require the stanfit object which you get via `read_stan_csv`. So in order to fix this one we would have to store only the requested parameters, which cmdstan does not support yet. 

So we either find a way to use cmdstanr without the stanfit object or we need to edit the csv.

2. The current minimum amount of output you get with quiet = TRUE and refresh = 0. Example below.

```
Compiling Stan program...
Running MCMC with 2 chain(s) on 2 core(s)...

Running bernoulli.exe "id=1" random "seed=123" data "file=C:/Users/Rok/AppData/Local/Temp/RtmpWGHqex/standata-3f9463f960b4.json" output \
  "file=C:/Users/Rok/AppData/Local/Temp/RtmpWGHqex/bernoulli-202005161159-1-ef1121.csv" "refresh=0" "method=sample" "save_warmup=0" "algorithm=hmc" \
  "engine=nuts" adapt "engaged=1"
Running bernoulli.exe "id=2" random "seed=124" data "file=C:/Users/Rok/AppData/Local/Temp/RtmpWGHqex/standata-3f9463f960b4.json" output \
  "file=C:/Users/Rok/AppData/Local/Temp/RtmpWGHqex/bernoulli-202005161159-2-ef1121.csv" "refresh=0" "method=sample" "save_warmup=0" "algorithm=hmc" \
  "engine=nuts" adapt "engaged=1"
Chain 1 finished in 0.3 seconds.
Chain 2 finished in 0.2 seconds.

Both chains finished successfully.
Mean chain execution time: 0.2 seconds.
Total execution time: 0.3 seconds.
```
this is with
```R
file <- file.path(cmdstan_path(), "examples", "bernoulli", "bernoulli.stan")
mod <- cmdstan_model(file, force_recompile = TRUE, quiet = TRUE)
data_list <- list(N = 10, y = c(0,1,0,0,0,0,0,0,0,1))
fit <- mod$sample(
  data = data_list,
  seed = 123,
  chains = 2,
  cores = 2,
  refresh = 0
)
```
We do have the `quiet` argument in a lot of our functions (see compile above) so adding it to $sample and other model functions does seem reasonable to me. Other packages that will want to use cmdstanr might want that also. 

`mod <- cmdstan_model(file, quiet = TRUE)` does output `Compiling Stan program...` or info that he model was already built. I am guessing you don't want that either?

**Comment by paul-buerkner** [comment]
(1) Ok. I will see what would be the best option for use in brms then.

(2) when I fit the following model with the brms cmdstanr branch

```
fit <- brm(count ~ zAge, data = epilepsy, backend = "cmdstanr")
```

I get (multiple of)

```
Chain 3 Informational Message: The current Metropolis proposal is about to be rejected because of the following issue:
Chain 3 Exception: normal_id_glm_lpdf: Scale vector is inf, but must be finite! (in 'C:/Users/paulb/AppData/Local/Temp/RtmpWiuZ5z/model-3848745a21b1.stan', line 34, column 4 to column 62)
```

These messages will appear sometimes for all kinds of models and lead to lots of questions on discourse without really helping much in addition to the usual convergence diagnostics.
I don't really mind other messages or output which does not irritate users all the time.

**Comment by rok-cesnovar** [comment]
(1) In theory there should not be much of a difference betwen what rstan::read_stan_csv returns and what read_sample_csv from cmdstanr returns. I will check what brms consumes from the stanfit.

(2) I think we could add an option to surpress these. These are written to stderr in cmdstan and the current policy is that what we get on stderr is written to the user even if quiet=TRUE. That is because we want to output any errors that would stop the model (missing data, chains failing to initialize). surpressWarnings or something like that.

**Comment by rok-cesnovar** [comment]
@jgabry should quiet = TRUE actually be quiet even for sampling warnings? If needed, users can examine output(). Or if a chain fails completely, we could print the last few lines of stderr? But not sure that is needed. This would fix (2) here.

Sorry for spamming you so much today :)

**Comment by jgabry** [comment]
> Sorry for spamming you so much today :)

It's great. None of it has been spam! It's nice to see so much getting done!

> @jgabry should quiet = TRUE actually be quiet even for sampling warnings? If needed, users can examine output().

Hmmm, maybe. I'm not sure about this. I understand why that would be nice, but it seems risky. How do we know which of the messages are important and which are safe to ignore? I think it's unlikely brms users will check `output()` after to see the warnings/messages. @paul-buerkner What do you do when rstan is the backend? Do you suppress everything?

**Comment by jgabry** [comment]
to follow up about this: I'm open to being convinced that it's a good idea to provide the option of turning these messages off. I just want to make sure we think about whether it's worth the risk

**Comment by paul-buerkner** [comment]
In `rstan` I am using the `show_messages` argument of `rstan`. I am not entirely sure what messages this suppresses but empiricially, it prevents printing out a lot of information that confuses users without really helping. Because if there is something that causes, e.g. initialization to fail, I still see the corresponding error.

**Comment by jgabry** [comment]
Ok, thinking about this some more, I think it's fine to provide an option that brms can use to turn off the "informational messages" like

```
Chain 3 Informational Message: The current Metropolis proposal is about to be rejected because of the following issue:
```

@rok-cesnovar like you suggested, we should recommend that users check `fit$output()` afterwards if there are issues.

**Comment by rok-cesnovar** [comment]
Ok great. Do we surpress with quiet or add show_messages?

**Comment by jgabry** [comment]
I guess `quiet` could be a bit misleading since we would still show output (e.g. iteration updates) so maybe `show_messages` makes more sense?
