### ISSUE TITLE
cmdstanr fit object doesn't contain samples

### ISSUE THREAD

**Issue by ssp3nc3r** [stan-dev/cmdstanr#174]
I'm not sure whether you want this logged as a bug, feature request, or document change, but it is not clear that the fit object, `fit_mcmc` in the example, does not contain actual samples, only file paths to read them. 

Implications are that when the fit object is saved, _e.g._, 

`saveRDS(fit_mcmc, "fit_mcmc.rds") 
`

and shared on another computer, it won't have access to the samples. Below I show the result of fitting the example model in the help files, transferring them to another computer, and attempting to get a summary of the samples:

```
> fit_mcmc$cmdstan_summary()
Running bin/stansummary \
  /var/folders/pg/qc4jx60s2ys3smt604547ckw0000gn/T/RtmpNc0Dqi/bernoulli-202005161343-1-05db98.csv \
  /var/folders/pg/qc4jx60s2ys3smt604547ckw0000gn/T/RtmpNc0Dqi/bernoulli-202005161343-2-05db98.csv
File /var/folders/pg/qc4jx60s2ys3smt604547ckw0000gn/T/RtmpNc0Dqi/bernoulli-202005161343-1-05db98.csv not found
File /var/folders/pg/qc4jx60s2ys3smt604547ckw0000gn/T/RtmpNc0Dqi/bernoulli-202005161343-2-05db98.csv not found
No valid input files, exiting.
```

Is the current or recommended approach to use the class function,

`fit_mcmc$save_output_files()`

to move `csv` files into the working directory, and then save the fit object together with the output files, and share the group of files together?

**Comment by mitzimorris** [comment]
I think this is a document change - this should be made clearer as part of the vignettes -
it is documented nicely at the function level:

see http://mc-stan.org/cmdstanr/reference/fit-method-save_output_files.html

but agreed, you need to understand what the outputs are, and why.  in this case, the CmdStanMCMC object only reads the sample into memory the first time you access the draws.  if you save the output files to a permanent location, you will be able to access them later, although you'd probably need to resolve filesystem access, etc.

**Comment by rok-cesnovar** [comment]
While writing this, I saw @mitzimorris already answered. Here is my answer anyway :)

Yes, the samples do not get read in the fit object automatically. That is by design. 

If you would do 

```R
fit <- mod$sample(...)
fit$draws()

saveRDS(fit, ...)
```

Then read the RDS on another system and call either `print(fit$draws())` or `fit$summary()`. Both would work and you would have all the samples, sampling info, etc.

`fit$cmdstan_summary()` however would not work, as it works only with the the CSV files directly. `$cmdstan_summary()` calls `bin/stansummary` of cmdstan which only works with CSV files.

Both should be documented a bit better, thanks for shedding light on that.

We could also make reading in all the samples automatically the default mode of operation. But I am not completely sure what is best there.

**Comment by ssp3nc3r** [comment]
> this should be made clearer as part of the vignettes

Agreed. I suspect users begin with the vignette,

Getting started with CmdStanR

Perhaps adding a short section at the end explaining a bit about workflow and what files are needed to share the resulting fit with others?
