### ISSUE TITLE
Read cmdstan version

### ISSUE THREAD

**Issue by rok-cesnovar** [stan-dev/cmdstanr#22]
We need a way of knowing which cmdstan version is running underneath. I can imagine there will be cases where we wont be able to avoid branching execution based on the version, unfortunately. 

I dont think this needs to be exposed to the user, just as an internal function. We can discuss details once I figure this out.

The easiest place to read it would be here: https://github.com/stan-dev/cmdstan/blob/a58ddcd179ff4ea865d2bf99445532a83c49a377/makefile#L47

**Comment by rok-cesnovar** [comment]
I am not able to assign myself for this one, probably need permissions or something. Consider this post as me assigning myself.

**Comment by jgabry** [comment]
I agree this is a good idea. And I just gave you more permissions, so you should be able to assign yourself now.

**Comment by jgabry** [comment]
Actually @rok-cesnovar I hope you don't mind but I just went ahead an implemented this because I was looking at the cmdstan makefile anyway and I had a spare couple of minutes. But feel free to change my implementation if you have a better idea. What I did is add this internal function to detect the version number: 

https://github.com/stan-dev/cmdstanr/blob/f26b3f37eeb51e10b40ad06c42f3beb01ce5b047/R/path.R#L89-L106

When the path to cmdstan is set by the user it will call this internal function and store the version number in `.cmdstanr$VERSION` (`.cmdstanr` is an internal environment) and it can then be accessed via the `cmdstan_version()` helper function (not exposed to the user although we could). 

So if branching ever needs to happen based on version number then we can do something like this:

```r
if (cmdstan_version() <= "2.20.0") {
  # do something
} else {
  # do something else 
}
```  

Anyway, feel free to change this implementation if you have a better idea!

**Comment by rok-cesnovar** [comment]
That is basically what I envisioned in my head but didnt have the time to do it in code yet. Thanks!

I dont have much time this week to code on cmdstanr with the coming cmdstan release, but will post issues if any good idea comes to mind, if you dont mind. If you finish any by the next week it fine by me :)

**Comment by jgabry** [comment]
Sounds great. Definitely open issues if you think of anything. Whenever you end up having time to code it will be appreciated, but no rush!
