### ISSUE TITLE
knitr engine for Stan chunks in R Markdown documents

### ISSUE THREAD

**Issue by bearloga** [stan-dev/cmdstanr#261]
Hello! The built-in knitr engine for Stan chunks relies on RStan, which may not work for everyone (especially not for CmdStanR users). I wrote a version of the engine that uses CmdStanR instead of RStan (and supports executable caching to prevent re-compiling every time the Rmd doc is knit/rendered) and demonstrate it here: https://mpopov.com/blog/2020/07/30/replacing-the-knitr-engine-for-stan/

I'm curious if the maintainers would be interested in providing something like this inside the package? Then R Markdown users can override the built-in, RStan-based engine by running something like `cmdstanr::register_knitr_engine()` at the top so whenever they have Stan chunks, those would go through CmdStanR's engine instead.

Here's a {distill} article as another example:

![distill](https://user-images.githubusercontent.com/1807519/89045336-59a74900-d319-11ea-961f-dd8cfc9df849.png)

I'd be happy to submit a PR, just wanted to check first.

**Comment by rok-cesnovar** [comment]
@bearloga this looks very nice and useful! Thanks for the feature request and extensive details and examples!

I will let @jgabry comment and decide on this one as I am a rookie in the knitr/vignetter/R docs universe.

**Comment by jgabry** [comment]
@bearloga This is great, thanks! I'm definitely open to including something like this if you want to submit a PR. In addition to the code, a short vignette demonstrating how to use this would be awesome. Could be something like your blogpost or your example above. 

(Maybe eventually we could get this natively in knitr like RStan support is, but since CmdStanR isn't on CRAN yet it seems premature to propose that to Yihui.)

**Comment by bearloga** [comment]
Awesome! Happy to have your blessings and also thank you so much for all the work you've done on this package!
