### ISSUE TITLE
`sampler_diagnostics()`: format and variables names 

### ISSUE THREAD

**Issue by gbiele** [stan-dev/cmdstanr#301]
The variable names and and format of nuts-sampler parameters are incompatible with what plotting functions of the posterior package expect. (I hope I didn't overlook a function in posterior that deals with that..)

The methods `sampler_diagnostics()` returns an array where the names for chain, iteration and draw are ".chain" ".iteration" ".draw" and parameters in different arrays. However posterior expects a "long form" data.frame with variables names Iteration, Parameter, Value, Chain.

Its of course not a problem to reformat this myself, but I think it would be convenient if  `sampler_diagnostics()` could also return data in a format the plotting functions of the posterior package can work with.

**CmdStanR version number**
cmdstanr_0.1.0

**posterior version number**
posterior_0.1.0

**Comment by jgabry** [comment]
Hey @gbiele, sorry for the delay! Just seeing this now. 

I think you meant to refer to the bayesplot package instead of the posterior package, right? If so, then if you install bayesplot from github you can use the method for CmdStanMCMC objects that I added in https://github.com/stan-dev/bayesplot/pull/227. Does that do what you were looking for?

**Comment by gbiele** [comment]
OK, got it.
Thanks for the pointer!
