### ISSUE TITLE
problems re-running Rmd files - Rmd caches holding on to runset info which references /tmp dir from previous run

### ISSUE THREAD

**Issue by mitzimorris** [stan-dev/cmdstanr#347]
**Describe the bug**

Not sure this is a bug or it's just the rmarkdown/knitr is stooopid.

It is necessary to remove Rmd `_cache` or `_file` directories between runs of rmarkdown

**To Reproduce**
Running from the command line:

```
Rscript -e "rmarkdown::render('bayes-versus.Rmd')"
```

throws error:

```
Quitting from lines 692-693 (bayes-versus.Rmd) 
Error in read_cmdstan_csv(files = self$output_files(include_failed = FALSE),  : 
  Assertion on 'files' failed: File does not exist: '/var/folders/db/4jnggnf549s42z50bd61jskm0000gq/T/RtmpjSyvaI/logistic-regression-202011131738-1-411d92.csv'.
Calls: <Anonymous> ... read_cmdstan_csv -> <Anonymous> -> makeAssertion -> mstop

Execution halted
```

It's necessary to remove the directories created by rmarkdown (or knitr) -  `_cache`  dir, because it's full of .RData, etc. files

```
ls bayes-versus_cache/html/
__packages
unnamed-chunk-15_64299c42a6e3760d74207166ff49b3c1.RData
unnamed-chunk-5_abffc4517facc59c2b5821ad5b090e00.rdb
...
```

**Expected behavior**

???

**Operating system**
mac Catalina

**CmdStanR version number**
cmdstanr 0.2.0

**Comment by mitzimorris** [comment]
only happens sometimes

**Comment by jgabry** [comment]
> Not sure this is a bug or it's just the rmarkdown/knitr is stooopid.

I'm not sure yet either. knitr tries to be smart about when it should use the cache vs when it needs to update but there are definitely cases when it messes up. It's also possible it's a cmdstanr issue, but I don't have an idea quite yet of what we could change to get it to work. 

> Rscript -e "rmarkdown::render('bayes-versus.Rmd')"

I tried to reproduce this problem with an Rmd file of my own but it didn't happen (maybe I just got lucky?). If possible can you send me the version of `bayes-versus.Rmd` that results in this problem?

**Comment by jgabry** [comment]
Hey Mitzi, so I cloned Bob's repo and checked out your branch. So far I haven't been able to reproduce the error. I've run it at least five times successfully. I know you said it only happens sometimes, so maybe I just haven't gotten (un)lucky yet. How often does it seem to happen for you?

**Comment by mitzimorris** [comment]
can't reproduce here either - closing

**Comment by wlandau** [comment]
For what it's worth, I have a use case where the error from https://github.com/stan-dev/cmdstanr/issues/347#issue-742858353 comes up. At work, I am building a package that wraps around a Stan model and uses `cmdstanr`. For me, the error only happens during `devtools::check()` and not during `R CMD check` or `devtools::test()`. I solved it by always setting `output_dir` to `fs::dir_create(tempfile())`. Any chance you be open to using `tempfile()` instead of `tempdir()` as the default location of the CSV files? I do not understand why this works for me, but at least I do not think `tempfile()` is any worse than `tempdir()`.
