### ISSUE TITLE
Clarify pre-reqs for install

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/cmdstanr#351]
@mitzimorris and I just tried to walk users through `cmdstanr` install from the instructions page and there are several key steps that are missing from the instructions page:

https://mc-stan.org/cmdstanr/#installation

* [ ] needs to point to `cmdstan` installation
* [ ] needs to say that the "beta" is 0.2.0 or whatever the recent number is
* [ ] needs to have `Rtools` installed before `devtools`
* [ ] for `Rtools`, we need to modify your path `PATH="${RTOOLS40_HOME}\usr\bin;${PATH}"`
* [ ] `https://cran.r-project.org/bin/windows/Rtools/`

* [ ] `devtools`: need to mention that needs to be installed
    - and if there are any pre-reqs to installing devtools, those also need to be mentioned
* [ ] we also need `dependencies = TRUE` to get `posterior`, etc., on which `cmdstanr` depends.  
`install.packages("cmdstanr", repos = c("https://mc-stan.org/r-packages/", getOption("repos")), dependencies = TRUE)` 
or we need to check the same in RStudio's installer
* [ ] need instructions to install `cmdstan`
`library(cmdstanr);`
`install_cmdstan(cores = 2)`
And we probably need to tell people that `cmdstan` is being installed in a hidden location they can find with `cmdstan_path()`

**Comment by jgabry** [comment]
Thanks Bob, that's really helpful. A few comments: 

Yeah in the readme we just have installation instructions for the R package, not for CmdStan itself. Those instructions are in the Getting Started vignette. To put that in the readme we'll need to duplicate the content because it's still essential to have it in the vignette too (if the package makes it to CRAN then unfortunately the github readme won't be included but the vignettes will, so we need the content in the vignettes). So I think what makes the most sense is to make it more clear in the readme that the CmdStan instructions are in the vignette instead of duplicating the content. You're definitely right that we don't currently explicitly say this (and we should!). 

As for requirements, yeah you're right it looks like RTools isn't mentioned, so we should definitely add that. That's an oversight. As for devtools, I didn't think that's required. As far as I know RTools can be installed without devtools. 

> * [ ]  we also need `dependencies = TRUE` to get `posterior`, etc., on which `cmdstanr` depends.
>   `install.packages("cmdstanr", repos = c("https://mc-stan.org/r-packages/", getOption("repos")), dependencies = TRUE)`
>   or we need to check the same in RStudio's installer

Adding `dependencies=TRUE` should not be necessary. If it is necessary then we need to look into that because the default settings of `install.packages` should result in all packages listed in Imports in the DESCRIPTION file getting installed (and that's where posterior is). If you look at the doc for install.packages it says for the `dependencies` argument:

> The default, NA, means c("Depends", "Imports", "LinkingTo").

so that includes posterior. If I do `remove.packages("posterior")` and then run the `install.packages` line without setting `dependencies=TRUE` it installs fine for me, as it should. Does that fail for you? 


> * [ ]  needs to say that the "beta" is 0.2.0 or whatever the recent number is

If you go the github.com/stan-dev/cmdstanr it has both the readme and (on the right side of the page) it also lists the latest release and says it's 0.2.0. Are you saying we also need to manually type that into the readme and change it every time we release? I'd rather not have manually edit the readme every time the number changes since github automatically lists it on the very same page.


> * [ ]  need instructions to install `cmdstan`
>   `library(cmdstanr);`
>   `install_cmdstan(cores = 2)`
>   And we probably need to tell people that `cmdstan` is being installed in a hidden location they can find with `cmdstan_path()`

This is all in the getting started vignette, so we'll make it more clear in the readme that the user needs to consult the vignette.

**Comment by rok-cesnovar** [comment]
Thanks for the feedback and "live testing".

> for Rtools, we need to modify your path PATH="${RTOOLS40_HOME}\usr\bin;${PATH}"

Do you mean on Windows? For cmdstanr this is not required. If the PATH is not properly set, `install_cmdstan()` suggests to the user to run `check_cmdstan_toolchain(fix = TRUE)` which fixes most common Windows issues, apart from installing RTools and permission issues.

> devtools: need to mention that needs to be installed

Is it actually required on some system? Just ran

```
remove.packages("devtools")
remove.packages("remotes")
remove.packages("posterior")
remove.packages("cmdstanr")

install.packages("cmdstanr", repos = c("https://mc-stan.org/r-packages/", getOption("repos")))
```
and it installed without a problem and it also installed posterior and the examples worked without a hitch. Will double-check if it's any different on Windows.
If you use install_github() there is probably more involved. But I would only suggest install_github() to those that know their way around installing from source.

Strong agree on all other points that Jonah hasn't already mentioned!

**Comment by jgabry** [comment]
> > devtools: need to mention that needs to be installed
> 
> Is it actually required on some system?

I would assume not since it would be very strange for devtools to be a requirement for RTools. RTools is maintained and distributed by core CRAN people whereas devtools is an RStudio/Hadley package and, as far as I know, will never be required for anything that is distributed by core CRAN.

**Comment by jgabry** [comment]
Ok after going through this list again I think the two items we definitely need to address are these: 

* [ ] needs to point to `cmdstan` installation

We'll do this by more clearly pointing to the getting started vignette instead of duplicating all the instructions in multiple places. 

* [ ] `https://cran.r-project.org/bin/windows/Rtools/`

I think we should just link to https://mc-stan.org/docs/cmdstan-guide/cmdstan-installation.html which has the toolchain requirements for Linux, Mac, and Windows. We already link there in the `help("install_cmdstan")` page but we should definitely link there in the installation instructions too since it describes prerequisites. 

Other than that I don't actually think the other items in the initial list are correct for the reasons in my initial response (but @bob-carpenter please correct me if I'm wrong). That said, we may need to look into some of them further if they're not working as expected (like the `dependencies` argument to `install.packages`).

**Comment by bob-carpenter** [comment]
I'm totally OK pointing to CmdStan installation instructions.  

Rather than duplicating instructions, can the readme just point to the getting started doc with full installation instructions?  Or could the install instructions be pulled out of the getting started doc into their own page.  I agree that we don't want to maintain duplicate instructions---it never ends well.

I wasn't the one installing, so I'm not sure about what was going on with the paths.  The people @mitzimorris and I were trying to help install finally got CmdStanR installed and running.  Turns out that once they got Rtools installed properly, everything else worked OK.

P.S.  Thanks for letting me know about dependencies.  I'm not sure if we tried it both ways or not.

**Comment by mitzimorris** [comment]
late to this party - I thought that devtools was still needed - didn't realize that it isn't.

as Bob said, the problems were with getting RTools installed - users on the forums say that only Max Mantei's blogpost helped them - but that post is now 404 and I've contacted him directly asking for a copy.

**Comment by mitzimorris** [comment]
> Do you mean on Windows? For cmdstanr this is not required. If the PATH is not properly set, `install_cmdstan()` suggests to the user to run `check_cmdstan_toolchain(fix = TRUE)` which fixes most common Windows issues, apart from installing RTools and permission issues.

indeed,  per `install_cmdstan()` suggestion, ran `check_cmdstan_toolchain(fix=TRUE)` - didn't work.
in my very limited experience with Windows users, the common problem _are_ RTools and permissions problems.
I couldn't find enough info on what they are and how to fix them.   I did suggest the `pacman` command per forums, but that didn't work here.

**Comment by rok-cesnovar** [comment]
If using R4.x, the only thing required is to: 

- install RTools
- run `check_cmdstan_toolchain(fix=TRUE)`

And the latter handles running the `pacman` command and setting up the path correctly. I have tested this on at least 4 clean systems. Even if the user has other compilers installed this should work.

The only problems that we can not fix is: 
- RTools is installed in a path with spaces

If someone does that, compiling any R package from source does not work. So if R devs have not figured this one out, I doubt we have the resources to do that. I strongly encourage to install RTools in the default folder (C:/rtools40).
- the user does not have permission in the RTools folder (reinstalling to default location fixes that)
- the user does not have permissions in the folder where we compile. A user recently had the temporary folder in `C:/Windows/temp` which is just outright weird. That is like having the temp folder in the same folder as the Linux kernel.

If there are other issues we would really like to know them.

**Comment by mitzimorris** [comment]
there are other issues - users on Windows 10 Pro

<img width="669" alt="Screen Shot 2020-11-18 at 3 23 35 PM" src="https://user-images.githubusercontent.com/5466612/99584583-244f6580-29b3-11eb-87e3-bc6273d1f9a3.png">

**Comment by rok-cesnovar** [comment]
Yes, I have seen this one. This is a permission issue, the user does not have write permissions in the RTools folder. The only way to get around this is to open the Windows shell as administrator and run the pacman command or reinstall RTools. Or running RStudio as administrator would also work I guess.

Will incorporate the check for permissions in the Rtools folder in the check_cmdstan_toolchain function.

**Comment by mitzimorris** [comment]
https://discourse.mc-stan.org/t/cmdstanr-installation-error-command-not-found-win-processx-c-977/11970

was this resolved?  can't tell from the discussion

**Comment by jgabry** [comment]
> Rather than duplicating instructions, can the readme just point to the getting started doc with full installation instructions? Or could the install instructions be pulled out of the getting started doc into their own page. I agree that we don't want to maintain duplicate instructions---it never ends well.

Yeah, good call. I'll add that to my PR #353. 

> I wasn't the one installing, so I'm not sure about what was going on with the paths. The people @mitzimorris and I were trying to help install finally got CmdStanR installed and running. Turns out that once they got Rtools installed properly, everything else worked OK.

Yeah RTools seems to be the culprit in the overwhelming majority of installation issues. The more we can do to help with that the better of course. Rok has automated a bunch of fixes but I think there are still a few potential issues that we don't know how to resolve on our end.

**Comment by mitzimorris** [comment]
>  the user does not have write permissions in the RTools folder. The only way to get around this is to open the Windows shell as administrator and run the pacman command or reinstall RTools. 

the user had admin privs and had installed latest RTools.   they were trying to work from within RStudio.

**Comment by mitzimorris** [comment]
> Yes, I have seen this one. This is a permission issue, the user does not have write permissions in the RTools folder. The only way to get around this is to open the Windows shell as administrator and run the pacman command or reinstall RTools. Or running RStudio as administrator would also work I guess.

the other thing to do would be to install RTools within the `.cmdstan` directory, which is the fallback option used in CmdStanPy's `install_cxx_toolchain` script

**Comment by rok-cesnovar** [comment]
Yes, but you need to run the shell with “as administrator”. The issue in the threas was resolved like that.

**Comment by mitzimorris** [comment]
I feel like there's a disconnect between the solutions here and what the user knows how to do.
it is on us to give the users solutions that are within their abilities, software install-wise.
a bunch of heuristics and instructions that say "try this; check that" is OK for students enrolled in some kind of cs or data science or similar program - maybe they'll muddle through and they have all the time in the world.
folks who are working on deadlines and juggling projects won't be able to use Stan.

although in this case, they'll be able to use RStan which doesn't run afoul of the mingw64 make issue in the same way.

**Comment by rok-cesnovar** [comment]
The issue here that this is a botched install of Rtools. Most likely it was installed with elevated privileges. And there is nothing we can do there apart from a nicer and more informative message. Its like if a user would install an R package with sudo on unix. Its not ideal.

Installing rtools in .cmdstan would work but not sure I am a huge fan of that really. Thats not a standard place a user would find an installed application.

In the thread I was trying to debug with the user, because it was the first time seeing this issue. Thats why it was a ton of “try this and that”.

The best solution would be to remove the mingw32-make requirement.

**Comment by rok-cesnovar** [comment]
This isnt a really common issue I would say. Most issues are now fixed by cmdstanr automatically.

**Comment by mitzimorris** [comment]
> Thats not a standard place a user would find an installed application.

C++ is an under-the-hood application, not something that users go looking for.
what matters is that CmdStan and wrappers can find the version of C++ they need in order to compile a program.

**Comment by mitzimorris** [comment]
> The best solution would be to remove the mingw32-make requirement.

what would this do?

**Comment by rok-cesnovar** [comment]
We would just need to supply the TBB Windows DLLs in the release tarballs.

**Comment by jgabry** [comment]
> We would just need to supply the TBB Windows DLLs in the release tarballs.

Are there any downsides to that? If there aren't any major downsides and that would fix this problem then it sounds like we should do that. But this is not my area of expertise so I will defer to the rest of you on this.

**Comment by mitzimorris** [comment]
are `mingw32-make` and `mingw64-make` two different things?
would users still need the latter?

**Comment by rok-cesnovar** [comment]
No, the only reason we need `mingw32-make` is to build the TBB. After `mingw32-make build` that builds the lib, we could technically allow the use of the plain `make`, but don't because that would just be confusing. 

> Are there any downsides to that?

I need to double-check the license discussion again (when we added TBB we had a bunch of discussions of how we can redistribute TBB under our license). I don't think distributing .dll files falls on the problematic side, but need to re-read it. 

Other than that there should not be an issue. It would add 2MB to the tarball size, but that should not be a problem.

**Comment by jgabry** [comment]
> Rather than duplicating instructions, can the readme just point to the getting started doc with full installation instructions?

Actually I looked over the getting started vignette and it already has the instructions for installing both the R package and for calling `install_cmdstan()` to install CmdStan. But it's definitely missing an explicit mention of the toolchain, which is obviously important! The toolchain is mentioned in the `install_cmdstan()` function doc, but we definitely need to mention the toolchain prominently in the getting starting vignette too. But other than that I think everything asked for is already in there. I'll go ahead and add the link to the section of the CmdStan guide where it goes over the toolchain requirements.

**Comment by jgabry** [comment]
This was closed automatically because my PR linked to this issue got merged. We can reopen to continue the discussion, but I think the topic of the issue "Clarify pre-reqs for install" was addressed so it might make more sense to start a separate issue to continue discussing the installation issues related to the toolchain (which is separate from clarifying what the pre-reqs are). Or we can continue that discussion here if it makes more sense to keep it all in the same place.

**Comment by jgabry** [comment]
Also I decided not to remove the R package installation instructions from the readme even though they're also in the vignette. It's not ideal to have it in both spots, but it's standard practice in the R world to have a section in the readme exactly as we had it, so I think that's a reason to keep it. So now we have the following: 

* The readme mentions how to install the R package and points to the Getting Started vignette for installing CmdStan. In case the user hasn't already successfully installed the R package this is also mentioned in the Getting Started vignette. I didn't remove it from the readme for the reason mentioned above. 

* The getting started vignette shows how to install the R package, tells the user they need a suitable toolchain and links to the CmdStan guide section on toolchain setup, and demonstrates the use of the install_cmdstan() function.
