### ISSUE TITLE
Formal @param entries for method arguments

### ISSUE THREAD

**Issue by wlandau** [stan-dev/cmdstanr#367]
It would be nice if methods like `$sample()` had formal `@param` entries for the arguments. Currently, they are documented in an informal list:

https://github.com/stan-dev/cmdstanr/blob/3b7fbe551617c5c6c30883df501cbb34ea07b865/R/model.R#L670-L772

Formal `@params` would allow packages built on top of `cmdstanr` to use `@inheritParams`. 

The reason I bring this up is that I am currently building a Bayesian data analysis framework on top of `cmdstanr` and [`targets`](https://github.com/wlandau/targets). The package is called `stantargets`, and I hope to make it open source within the next week or two (currently waiting for the required approvals).

**Comment by jgabry** [comment]
I totally agree but unfortunately I've found the R6 support in roxygen2 to be insufficient for the complexity of the cmdstanr doc. That said I haven't checked if they've improved it since last year when they first introduced it. I opened this issue at the time https://github.com/stan-dev/cmdstanr/issues/81 and I even started a few branches trying to do the conversion but I stopped because it was just much easier to do it this way and gave us a lot more control over the doc. Do you know if they've made improvements since then?

**Comment by jgabry** [comment]
Quick update: I checked and it looks like https://github.com/r-lib/roxygen2/issues/931 is still open. So that presumably means roxygen2 still doesn't support documenting methods for R6 classes that are defined using `$set()`, which is one of the main issues preventing us from using the R6 support in roxygen2. 

@wlandau If you have any suggestions for how we can work around that then I'm definitely open to trying. I agree that it's unfortunate that we don't have the standard usage of `@param`.

**Comment by wlandau** [comment]
In that case, I agree: if `cmdstanr` still needs dynamically add methods, then it seems like there is nothing we can do until https://github.com/r-lib/roxygen2/issues/931 is solved. I would like to revisit this issue when that happens, but feel free to close this one if that's your policy.

**Comment by rok-cesnovar** [comment]
Marked it with a future milestone and we will revisit once roxygen2 supports methods defined using `$set()`

**Comment by jgabry** [comment]
I suppose we could just switch now to not using `$set()`, but that's a nice feature of R6 that allows for the codebase to be a bit nicer in my opinion. If we don't use it then we have to define all the methods when the class is initially set up via `R6Class()`, even if the code for the method is substantial. Currently we tend to define simple methods initially with the class and more complicated ones separately and then add them via `$set()`. 

So the advantage of not using `$set()` would be that we could probably use the current roxygen2 support for R6 objects (although there may be other issues with it that we'd encounter). The advantage of waiting for roxygen2 to support methods via `$set()` is that we don't need to change the way we keep the codebase.

**Comment by rok-cesnovar** [comment]
Would adding functions that just call the bigger functions to the class? Or would that be too weird?

**Comment by jgabry** [comment]
Hmm, do you mean like this?

```r
R6::R6Class(
  ...,
  sample = function(x, y, z) {
    sample_method(x = x, y = y, z = z)
  }
)
```

If so, yeah that would be weird but I guess it could work.

**Comment by rok-cesnovar** [comment]
Yes, like that.

**Comment by rok-cesnovar** [comment]
If that helps with documentation and user-facing help then we maybe should consider it, regardless of its weirdness?

**Comment by jgabry** [comment]
Yeah I don't love it, but I definitely think the user experience of the documentation is important so I'm not totally opposed to this if it makes it easier to do the doc and user-facing help.

**Comment by jgabry** [comment]
Actually I just tried this and it doesn't quite work: 

```r
test <- R6::R6Class(
  "test",
  public = list(
    f = function(x) {
      internal_method(x = x)
    }, 
    z = 3
  ),
  private = list(
    y = 2
  )
)
internal_method <- function(x) {
  x + private$y + self$z
}

test$set("public", "g", internal_method)

A <- test$new()
A$f(1) # error
A$g(1) # works correctly
```

Here `f` doesn't work because it doesn't know what `private` and `self` are. But setting the method via `set()` like for `g` works. I suppose we could maybe get around this if we explicitly pass `self` and `private` as arguments to all of the internal functions, but that seems like a real hack if it just works out of the box via `set()`. Maybe it's worth it for the documentation, but I'm also not sure if there are potentially downsides to passing around self and private everywhere (I haven't even tested that that works, but I suppose it would).

**Comment by rok-cesnovar** [comment]
Ah yes, self and private...

Then scratch that. I dont like passing them in.

**Comment by wlandau** [comment]
What about an orphaned docstring?

```r
#' @title Run MCMC ...
#' @name model-method-sample
#' @description Run MCMC ...
#' @param data ...
#' @param chains ...
NULL
```

**Comment by jgabry** [comment]
That's a good idea. Do you know if will CRAN complain about that (we do eventually want to put cmdstanr on CRAN if possible)? I guess that probably would be fine. I know CRAN's check complain if there's a mismatch between function arguments in the code and doc but I guess if there's no function at all then it's fine?

**Comment by wlandau** [comment]
I used an orphaned docstring at https://github.com/EliLillyCo/rfacts/blob/main/R/facts_engines.R to avoid having to repeat shared arguments, and CRAN accepted it as is. Then again, I had [`@rdname`s referring to it](https://github.com/EliLillyCo/rfacts/blob/69320ed37d68dbff9f168d88febb3a146d2a0d50/R/run_engine_contin.R#L2), which was natural in my case.

**Comment by jgabry** [comment]
Ok cool, then I think we should definitely try this.

**Comment by wlandau** [comment]
By the way, I have a new package on GitHub called [`stantargets`](https://github.com/wlandau/stantargets), an extension to [`targets`](https://github.com/wlandau/targets) for Stan-powered Bayesian data analysis. [`stantargets`](https://github.com/wlandau/stantargets) makes it super easy to set up useful [`targets`](https://github.com/wlandau/targets)-powered pipelines to manage the workflow and skip expensive computation when the results are already up to date. It supports all the features of [`cmdstanr`](https://github.com/stan-dev/cmdstanr) (MCMC, variational Bayes, optimization), and it supports both single-fit workflows and multi-rep simulation studies ([vignettes here](https://wlandau.github.io/stantargets/articles/index.html)).

**Comment by jgabry** [comment]
Very cool! I'm really happy to see a package like that. Is https://github.com/stan-dev/cmdstanr/issues/340 also related to stantargets? If the serialization is a bottleneck at the moment then we can make that issue more of a priority.

**Comment by jgabry** [comment]
(oops accidentally closed, just reopened)

**Comment by wlandau** [comment]
Thanks! #340 is related, but it's not a big deal for `stantargets` because it is easy to [just call `$draws()` etc. directly](https://github.com/wlandau/stantargets/blob/fdd665ada0ae70826941310b27fa6725f6a86c17/R/tar_stan_mcmc.R#L446-L450).

**Comment by jgabry** [comment]
> What about an orphaned docstring?

@wlandau I've started working on your orphaned docstring idea on a branch, but either I'm doing something wrong (totally possible) or `@inheritParams` doesn't actually work with orphaned docstrings (which would be a bummer since that's part of the motivation). You can see that I changed the `sample` method to use `@param`: 

https://github.com/stan-dev/cmdstanr/blob/c4bc1178d0db649e00882975c95131ab85da7e4c/R/model.R#L725-L728

but when I then try to inherit those params for the `sample_mpi` method: 

https://github.com/stan-dev/cmdstanr/blob/c4bc1178d0db649e00882975c95131ab85da7e4c/R/model.R#L994-L1000

I get a warning from roxygen2: 

```
Warning message:
Topic 'model-method-sample_mpi': no parameters to inherit with @inheritParams 
```

Any ideas?

**Comment by jgabry** [comment]
Actually immediately after posting the previous message it occurred to me that the problem probably isn't that the sample method uses an orphaned docstring but rather that sample_mpi does. Inheriting params _into_ an orphaned docstring probably won't work since it won't know which params to inherit (there's so function signature that it knows about).

**Comment by jgabry** [comment]
I can work around this by just using royxgen templates for arguments I need in multiple orphaned docstrings, so I don't think it prevents us from continuing down this path.

**Comment by wlandau** [comment]
Sorry I am late to reply to this. 

> Actually immediately after posting the previous message it occurred to me that the problem probably isn't that the sample method uses an orphaned docstring but rather that sample_mpi does. Inheriting params into an orphaned docstring probably won't work since it won't know which params to inherit (there's no function signature that it knows about). I was hoping it would just import all of them.

One (non-orphaned) alternative is to write a fake/empty function with a signature instead of writing `NULL` in the docstring, then use `@keywords internal` to hide the fake function from the user.

> I can work around this by just using royxgen templates for arguments I need in multiple orphaned docstrings, so I don't think it prevents us from continuing down this path.

Seems possible but may require a lot of manual work if you need to manually duplicate `@param` entries among orphaned docstrings.

**Comment by jgabry** [comment]
> Sorry I am late to reply to this.

You gave me same day response, so that's pretty great! Sometimes it takes me a *lot* longer than that to respond to issues when I get busy, although I wish I could respond to them all immediately.
