### ISSUE TITLE
coordinate with CmdStanPy - single `.cmdstan` dir for install of CmdStan 

### ISSUE THREAD

**Issue by mitzimorris** [stan-dev/cmdstanr#454]
discussed with Jonah but failed to file issue - filing now:  https://github.com/stan-dev/cmdstanpy/issues/262

**Comment by jgabry** [comment]
I think we should make this change but before we do it we need to decide on how the change will work from the user's perspective since this is a breaking change. 

Here are two options that come to mind, but neither is ideal: 

#### Options

1. CmdStanR can just check for the `.cmdstanr` directory at startup, automatically rename it to `.cmdstan`, and notify the user

2. We could ask the user interactively if they approve of CmdStanR moving their installations. To do that we can use something like this

```r
utils::select.list(
  title = paste0("CmdStanR now uses directory '.cmdstan' instead of '.cmdstanr'.\n", 
                "Allow CmdStanR to automatically move your CmdStan installations?"),
  choices = c("Yes (automatically move my CmdStan installation(s) from .cmdstanr to .cmdstan)", 
              "No (I'll do it myself)"),
  graphics = FALSE
)
```

which produces the following in the console

```r
CmdStanR now uses directory '.cmdstan' instead of '.cmdstanr'.
Allow CmdStanR to automatically move your CmdStan installations? 

1: Yes (automatically move my CmdStan installation(s) from .cmdstanr to .cmdstan)
2: No (I'll do it myself)

Selection: 
```

#### Problems

The problem with (1) is that the user has no control over changes made on their computer

The problem with (2) is that it would only really work if CmdStanR is being used interactively, so what would we do if it's being run just from a script with no user to select an option? 

----

@rok-cesnovar @mitzimorris Any other ideas or comments on these options?

**Comment by rok-cesnovar** [comment]
I think we should move to .cmdstan on subsequent install of cmdstan. Meaning that any new install will go to .cmdstan and when cmdstanr will go checking for cmdstan installations the check will go in this order: 
1. check if .cmdstan exists. If found pick the latest cmdstan install in .cmdstan and finish, else go to 2
2. check .cmdstanr folder and pick the latest cmdstan installed in .cmdstanr folder
3. error as no installation was found

I would not try to move existing installations.

**Comment by jgabry** [comment]
That's a better idea! Alternatively we could wait and do this at the same time as the 1.0 release and then just make the breaking change of ignoring `.cmdstanr` entirely (that way we don't need to implement looking in multiple places). I'm ok either way. Preference?

**Comment by rok-cesnovar** [comment]
I think we should support both until 1.0 and once we do 1.0 just remove step 2 (ignore .cmdstanr).

**Comment by jgabry** [comment]
> * error as no installation was found

I think we should keep the current behavior of telling the user to manually set the path instead of erroring, but otherwise I think I have this implemented. Just one remaining question. If the user only has a `.cmdstanr` directory should we throw a warning alerting them to this change? Or should this all happen silently in the background?

**Comment by rok-cesnovar** [comment]
I think silently is fine? No strong preference though. we also dont warn users to remove old installs

**Comment by jgabry** [comment]
@mitzimorris Finally got around to doing this! Open PR is #520

**Comment by jgabry** [comment]
> I think silently is fine? No strong preference though. we also dont warn users to remove old installs

Ok yeah for now I didn't include a warning, but we could add one later if we want.
