### ISSUE TITLE
Please treat 1D table objects as vectors

### ISSUE THREAD

**Issue by gusl** [stan-dev/cmdstanr#527]
**Is your feature request related to a problem? Please describe.**
Sometimes one of the inputs is a table of bucketed counts, which should clearly be treated as a numeric vector, but cmdstanr can't handle it.

**Describe the solution you'd like**
Automatically call as.numeric() if it's a 1D table.
For 2D tables, maybe automatically call as.matrix().

**Describe alternatives you've considered**
Alternative: give a clear error message about needing to convert the table to numeric.  The "asJSON" part is distracting and obscures what needs to happen.

**Additional context**
Add any other context about the feature request here.

**Comment by jgabry** [comment]
@rok-cesnovar I can implement this. Do you prefer automatically converting tables or an informative error message? Either is fine by me.

**Comment by rok-cesnovar** [comment]
I think converting should be simple? I would go with that first if possible.

**Comment by jgabry** [comment]
Yeah it's pretty simple, although there's a little bit of R weirdness here. In the case of 2-D tables we can't use `as.matrix` because that preserves the "table" class (`as.matrix(table)` is still a table for some reason) and we can't use `as.array` for 3-D tables for the same reason. So I think we need to remove the table class with `unclass(table)` instead of calling functions like `as.matrix`. Opening a PR now.
