### ISSUE TITLE
Implement `posterior::as_draws()` for cmdstanr objects

### ISSUE THREAD

**Issue by mjskay** [stan-dev/cmdstanr#532]
Per the conversation at https://github.com/stan-dev/posterior/issues/183, now that {posterior} is on CRAN it would be wonderful if cmdstanr's objects could have an implementation of `posterior::as_draws()` so that users would not have to remember what function to call to get draws objects out of models when moving between packages. Perhaps this could be a simple wrapper around the `$draws()` method? Thanks!

**Comment by jgabry** [comment]
Sorry for the delay on this. I'm going to tackle this soon. 

Is the idea to add each of the `as_draws_*` functions (e.g. `as_draws_array()`, `as_draws_df()`, etc.) or just the single `as_draws()`? Judging from the conversation in stan-dev/posterior#183 it seems like I should implement all the `as_draws_*` functions, right? However, just having the `as_draws()` function could be sufficient since it gives the user a draws object that they can then convert to other formats using the standard functions in posterior. 

I'm open to either option. @rok-cesnovar @mjskay @paul-buerkner any preference? 

Also it sounds like from the discussion in stan-dev/posterior#183 we should have arguments `inc_warmup` and `variables`, so I can add those (which can just be passed to CmdStanR's draws() method).

**Comment by mjskay** [comment]
I guess it depends on if you either (1) have need for extra parameters like brms does or (2) have more efficient implementations of those functions than the generic implementations in posterior will be. If no to both, I think you can just add an as_draws() implementation that converts to the closest format, and the generics for posterior::as_draws_XXX() will call down to as_draws() anyway, so users will still be able to use as_draws_XXX() directly on cmdstan objects.

**Comment by jgabry** [comment]
Finally have a PR for this: https://github.com/stan-dev/cmdstanr/pull/581

**Comment by jgabry** [comment]
Since this is just a wrapper around `fit$draws()`, I ended up just using `...` as the only argument, which allows any of the arguments supported by `fit$draws()`.
