### ISSUE TITLE
[PATCH] CmdStanR on Windows 10, apparent lack of quoting path for grep.exe

### ISSUE THREAD

**Issue by robert-dodier** [stan-dev/cmdstanr#562]
I am working with Windows 10, R 4.1.0, CmdStan 2.27, CmdStanR 0.4.0.

I am running CmdStanR in an R session launched via `R --vanilla` from a Git bash terminal.

After setting up the model and data, I call `sample` and I get what appears to be normal output, it starts with

```
Model executable is up to date!
Running MCMC with 1 chain...

Chain 1 WARNING: There aren't enough warmup iterations to fit the
Chain 1          three stages of adaptation as currently configured.
Chain 1          Reducing each adaptation stage to 15%/75%/10% of
Chain 1          the given number of warmup iterations:
Chain 1            init_buffer = 15
Chain 1            adapt_window = 75
Chain 1            term_buffer = 10
Chain 1 Iteration:   1 / 300 [  0%]  (Warmup)
Chain 1 Iteration:  10 / 300 [  3%]  (Warmup)
```
(so far, so good, that's what I expected to see), and eventually says:
```
Chain 1 Iteration: 290 / 300 [ 96%]  (Sampling)
Chain 1 Iteration: 300 / 300 [100%]  (Sampling)
Chain 1 finished in 194.0 seconds.
'C:/Program' is not recognized as an internal or external command,
operable program or batch file.
Error: Supplied CSV file is corrupt!
```
Looks like it's trying to invoke an external program somewhere on the way to saving its csv file of results; it looks like the path to the executable is not sufficiently quoted, so `C:/Program Files/Foo/foo.exe` is getting messed up.

Looking at cmdstanr/R/csv.R, looks like `foo.exe` is `grep.exe` here. By the way, I think the error message in csv.R can be improved. Instead of saying "the file is corrupt!", how about "failed to read CSV file metadata" or something.

Here's a patch which fixed the problem for me. After applying this patch, `sample` runs to completion and produces apparently valid output.
```
$ git diff
diff --git a/R/utils.R b/R/utils.R
index 4da37d4..122f27c 100644
--- a/R/utils.R
+++ b/R/utils.R
@@ -93,7 +93,27 @@ repair_path <- function(path) {
     # remove trailing "/"
     path <- substr(path, 1, nchar(path) - 1)
   }
-  path
+
+  # If the path contains a space, and it is not already quoted,
+  # then enclose in quotes.
+  substring (path, 1, 1) -> first.char
+  nchar (path) -> n
+  substring (path, n, n) -> last.char
+  (first.char == '"' || first.char == "'") -> first.quote
+  (last.char == '"' || last.char == "'") -> last.quote
+  first.quote && last.quote -> is.quoted.path
+  if (grepl (" ", path, fixed=T) && !is.quoted.path) {
+    # I SUPPOSE AT THIS POINT WE SHOULD ENSURE THAT PATH
+    # DOES NOT ALREADY CONTAIN A QUOTE SOMEWHERE OTHER THAN
+    # THE BEGINNING OR END ... I CAN'T BRING MYSELF TO DO IT RIGHT NOW
+    paste0 ('"', path, '"') -> quoted.path
+    print (paste0 ("repair_path: quote -->", path, "<-- to get -->", quoted.path, "<--"))
+    quoted.path
+  }
+  else {
+    print (paste0 ("repair_path: -->", path, "<-- contains no spaces or is already quoted."))
+    path
+  }
 }

 #' Get extension for executable depending on OS

```

**Comment by rok-cesnovar** [comment]
Hey @robert-dodier, thanks for the report!

This would suggest you have the Windows RTools installed in a folder with spaces. What is the output of `Sys.getenv("RTOOLS40_HOME")`?

As far as I know, building any R package with Rtools installed in a path with spaces is problematic which is why we throw an error in `install_cmdstan()` in that case. Maybe this has changed in the last year and we need to lift that restriction though.

Also if you have the time, please run `check_cmdstan_toolchain()` and please paste the output you get. Thanks again!

**Comment by robert-dodier** [comment]
Hi Rok, it occurs to me that maybe it makes sense for `sample` to call `check_cmdstan_toolchain` before getting started since it is a long-running process and it's inconvenient for the user to get through the sampling and then fail afterwards.

**Comment by rok-cesnovar** [comment]
> it wouldn't hurt to say, at that point, what "properly" means in this context

Good call, will try to expand that a bit, without going too deep.

> So maybe the problem is that ~/.Renviron is not getting loaded

That would seem so yeah. This seems weird to me though. We are kind of counting on that to be the case.
Will look into that if we have to make a different plan.

What `check_cmdstan_toolchain()` does in your case is it prepends PATH with the path to RTools40. With that, we make sure 
the Rtools Unix-like tools will get picked up. For grep that doesnt really matter, as any grep tool will do. The main reason
we have that is so that g++ and the entire C++ toolchain is used from RTools. There it matters as users get all sorts of 
compile-time errors if it picks up Cygwin-supplied C++ compiler or similar.

> it occurs to me that maybe it makes sense for sample to call check_cmdstan_toolchain before getting started since it is a long-running process and it's inconvenient for the user to get through the sampling and then fail afterwards.

This is the backup plan for now yeah.
