### ISSUE TITLE
cmdstanr version number reported by packageDescription doesn't exist in Git

### ISSUE THREAD

**Issue by robert-dodier** [stan-dev/cmdstanr#593]
In an effort to match the version in use by a coworker, I tried to find a Git tag corresponding to the version they are using, which is 0.4.0.9000. However, I find there is no such tag. I also tried and failed to match up the presence of 0.4.0.9000 in DESCRIPTION with the Git log.

I eventually figured out that I should look at the Git commit hash in another field, and successfully installed that version. So that's a workaround.

I realize that 0.4.0.9000 is probably understood by the CmdStanR developers to mean an indeterminate version later than 0.4.0, however, outsiders are not going to understand that. My advice is to change the version number in DESCRIPTION to something that makes it more obvious that it's not a real version number. A possibility is post-0.4.0 or 0.4.0-post or post-0.4.0-<hash> or something.

**Comment by jgabry** [comment]
> I realize that 0.4.0.9000 is probably understood by the CmdStanR developers to mean an indeterminate version later than 0.4.0, however, outsiders are not going to understand that.

We've been using this because it's become standard in the R community due to recommendations like this one from Hadley Wickham: 

https://r-pkgs.org/release.html#release-version

To give a few examples (there are many more), the current version on github master branch of ggplot2, one of the most popular R packages is 3.3.5.9000:

https://github.com/tidyverse/ggplot2/blob/6704ea1fd01369445e7d28946edb8312c133691d/DESCRIPTION#L2

The current version for dplyr, another of the most popular package is 1.0.7.9000:

https://github.com/tidyverse/dplyr/blob/main/DESCRIPTION

So this practice is pretty common among the major R packages and familiar in the R community. 

> My advice is to change the version number in DESCRIPTION to something that makes it more obvious that it's not a real version number.

I think that's what the 9000 is supposed to convey, but I understand if that's not clear if you're not familiar with the convention. 

> A possibility is post-0.4.0 or 0.4.0-post or post-0.4.0- or something.

This is not allowed unfortunately. If we put this in the description file the package would error with `Error: invalid version specification ‘0.4.0-post’`.

**Comment by jgabry** [comment]
Just wanted to also say that we're definitely open to alternatives, but we have to stay within what's allowed for R package version numbers: 

https://r-pkgs.org/description.html#version

I think that means we are restricted to numbers (we can't use `"post"` or `"devel"`), which is why I think the `.9000` trend started.

**Comment by robert-dodier** [comment]
I understand that the n.n.n.9000 is a version numbering convention, but I don't think it's reasonable for anyone who is not an R package developer to know about it. I do a lot of software development, but I didn't know about that, so I spent a certain amount of time trying to figure out how to match the stated version to a specific software version. Okay, now I know.

I understand that package developers are constrained by what R allows. That's unfortunate, oh well, I don't have any desire to try to change it. At this point, I think my only advice is to somehow drop a line into DESCRIPTION to somehow say that n.n.n.9000 isn't a real version number, and people should look at the Git hash (I forget the field name) for that.

**Comment by jgabry** [comment]
> but I don't think it's reasonable for anyone who is not an R package developer to know about it.

Yeah that's fair. 

> At this point, I think my only advice is to somehow drop a line into DESCRIPTION to somehow say that n.n.n.9000 isn't a real version number

That's a possibility. I'll try to think of some other options too. @rok-cesnovar Do you have any ideas for how we can manage this better going forward?

**Comment by rok-cesnovar** [comment]
I think the issue will go away once by itself once we publish on CRAN. If we would update the r-packages package regularly it would probably also not be a real issue. 

I think the users should look at it this way: 

- CRAN (stan-dev/r-packages) release has proper versioning and users that care about using the exact same versions should use those. Those will also be considered stable.

- The Github version via `install_github()` should always be considered a development version (and noted with a .9000 once a change is made after a release.

- If someone wants to use the Github version and make sure they are using the exact same version, they should just specify the git hash.

We were not very diligent with bumping versions during development, but I think this is now in the rear view mirror mostly.

**Comment by robert-dodier** [comment]
Rok, thanks for taking the time to reply.

I don't know what to say, except to repeat what I said before. There's no way for ordinary users to know all that stuff. You, the package developers, have to (if you want) to figure out a way to label things in a non-misleading way. I don't know what that way is.

I do a lot of software development, and I am pretty far from naive as a consumer of other people's software. Yet I didn't realize, until after wasting time trying to track down a software version corresponding to the advertised version number, that it's not the version number that counts. I think this is evidence that statements about what the users should know are not well-founded.

Since this discussion doesn't appear to be progressing in any direction, I'll close it at this point and we can all give it a rest.
