### ISSUE TITLE
document how to get draws as df using "format=df"

### ISSUE THREAD

**Issue by mitzimorris** [stan-dev/cmdstanr#616]
We need more documentation around working with the returned sample.

here's an example from reworking Bob's case study on partial pooling for binary trials:

```
...
# create CmdStanMCMC object 'fit_hier'
...
# extract model fit as R dataframe/ tibble for ggplot2
hier_df = fit_hier$draws(format="df");

bda_plot <- function(df, x_lab, y_lab) {
  ggplot(df, aes(x=x, y=y)) +
    geom_point(shape=19, alpha=0.15) +
    xlab(x_lab) +
    ylab(y_lab) +
    theme_jupyter();
}

# note: must quote column names that look like indexed expr
inv_logit <- function(u) { 1 / (1 + exp(-u)); }
df_funnel <- with(hier_df, 
                  data.frame(x = inv_logit(hier_df$'theta[1]'), 
                             y = log(kappa)))
plot_funnel <- 
  bda_plot(df_funnel, 
           x_lab = expression(paste(logit('theta[1]'))), 
           y_lab = expression(paste(log(kappa))));
plot_funnel;
```

is there a way around having to quote 'theta[1]' ?

**Comment by jgabry** [comment]
I definitely think we need more examples of working with posterior draws, but this particular issue of getting draws as a df is already documented in multiple places: 

* In the main CmdStanR vignette in the _Posterior draws_ section there's a demonstration of specifying `format="df"`: https://mc-stan.org/cmdstanr/articles/cmdstanr.html#posterior-draws-1
* In the doc for the `draws` method the `format` argument doc mentions the `"df"` format: https://mc-stan.org/cmdstanr/reference/fit-method-draws.html 


> is there a way around having to quote 'theta[1]' ?

I don't think it's avoidable in this case because the `[1]` is part of the variable name here. You can use backticks instead of quotes (e.g., hier_df$`theta[1]`) but you have to use either backticks or quotes to make sure the `[1]` is interpreted as part of the name and not an index.

**Comment by jgabry** [comment]
Closing this since format="df" is documented in multiple places (see my previous comment), but I'll open a new issue to discuss where and how to best document working with the returned draws.
