### ISSUE TITLE
Add method laplace_sample 

### ISSUE THREAD

**Issue by jgabry** [stan-dev/cmdstanr#760]
Introduced in CmdStan 2.32. See CmdStanPy discussion: https://github.com/stan-dev/cmdstanpy/issues/649#issue-1549250952

**Comment by jgabry** [comment]
Or maybe this should just be an argument to `optimize` that results in samples being returned (rather than the user having to first call `optimize` and then `laplace_sample` we do it internally)? We should coordinate with the CmdStanPy people on this (@mitzimorris @WardBrian) so that we keep the interfaces consistent.

**Comment by jgabry** [comment]
Related to #761 because in order to get a sample optimize should be run with jacobian turned on.

**Comment by WardBrian** [comment]
I've also been thinking about this. It seems like it would be nice to be able to do it either way, but supporting both has some annoyances (e.g. the use of `optimize(samples=1000)` vs `optimize(...)`, `laplace(previous_result)`, the first one the result of laplace is part of the returned object in optimize, but in the second it would be a new object. Sort of annoying).

I suppose the alternative option is something like exposing laplace as either an argument to `optimize()` _or_ a method on the existing optimization return object. Then the logic is always inside the optimize object, rather than possibly being in two places

**Comment by WardBrian** [comment]
From today's Stan meeting:

We decided there are two use cases we want to support. In the first, you just want the laplace samples, in the second, you have an existing optimization result and want approximate samples from that mode. 

The method that seems to make the most sense (i.e. has the least code duplication, conditionals, etc) is a new method on the model object called `laplace_sample`. Modulo additional arguments for things like output file names, the signature would be (forgive the python)

`laplace_sample(data, mode: Optional[CmdStanMLE]=None) -> CmdStanLaplace`

If mode is `None`/missing, we will run optimization for the user, with jacobian=True, and then use that result for the laplace sampling. This will look like one step to the user.

If `mode` is supplied, we will use the supplied object as the mode rather than running optimization ourselves. We should check that `jacobian` was `True`, and issue a (warning|error?) if not. 

Over time, `mode` can be reasonably extended to accept things like a path to a CSV, a JSON file, a dictionary which we serialize to JSON, etc. 


For the `CmdStanLaplace` return object, it will look pretty similar to, for example, the existing `CmdStanMCMC` or `CmdStanGQ` objects, where you can get draws out etc. I think it also makes sense to have a `mode()` function or property which returns either the mode you passed us _or_ the mode we found from optimization if we ran it internally.

**Comment by avehtari** [comment]
The first comment is a feature a hope is available from the start
- For draws from the normal distribution, provide also __log_p and __log_q, where the latter is the (unnormalized) density wrt normal approximation. This can be used to assess the accuracy of the normal approximation and do importance weighting.

I'm adding the following comments that I hope are useful for planning the interface as these are natural extension (and speedups), but I don't suggest these should be implemented immediately
- Allow returning the Hessian at the mode (this is useful for many purposes, and estimating it from the draws has lower accuracy). This will require thinking a bit about IO
- Allow deterministic sample, e.g. a) quasi Monte Carlo sample has lower MCSE than random draw, b) central composite design (CCD) draw minimizes the number of density evaluations, but often provides sufficient accuracy, and is the minimal approach for obtaining useful posterior sd and certain quantile estimates for the constrained parameters,
- Allow split-normal approximation at the mode (Geweke, 1989)
- Combining split-normal and CCD is what INLA software has implemented and is useful for very costly log density evaluations and has better accuracy than plain normal approximation. L-BFGS often needs less than 100 target + gradient evaluations, and if we would sample 1000 random draws from the normal, the total computation is tenfold compared to running L-BFGS, while with split-normal-CCD, e.g., up to 8 dimensions we need only 97 log density evaluations with total computation being only twofold compared to running L-BFGS.

**Comment by WardBrian** [comment]
> For draws from the normal distribution, provide also __log_p and __log_q, where the latter is the (unnormalized) density wrt normal approximation. 

These are part of the output from the laplace service, so they will be available.

As an aside, they're provided as the _last_ two columns of the output CSV, breaking from the convention of all the other method ouputs, and they don't end with `__`, so it will break if a user has a parameter called `log_p`. Fun!
