### ISSUE TITLE
Dimensions dropped from data object, causing exception

### ISSUE THREAD

**Issue by cdriveraus** [stan-dev/cmdstanr#96]
In my stan model I have a data object like:
matrix[ntipred ? nsubjects : 0, ntipred ? ntipred : 0] tipredsdata;

When ntipred is 0, and hence it is a 0x0 matrix, cmdstanr seems to drop one of the 0 dimensions from the tipredsdata object. In R the structure of the object is correct, num[0 , 0 ] , but cmdstanr reports it as dims found = (0) . 

"Exception: mismatch in number dimensions declared and found in context; processing stage=data initialization; variable name=tipredsdata; dims declared=(0,0); dims found=(0) "

**Comment by rok-cesnovar** [comment]
Thanks for reporting. So just to make sure you are inputing a R data.matrix of size 0,0?

**Comment by cdriveraus** [comment]
Correct.

**Comment by bbbales2** [comment]
@rok-cesnovar do you know how to pass zero by zero matrices into the json Cmdstan?

If that's not possible, can we switch back to using stan_rdump until the 0x0s are okay with json? Should just be a matter of making a copy of the function here:

https://github.com/stan-dev/cmdstanr/blob/master/R/utils.R#L261

and changing the json write to:

```stan_rdump(names(data), file, env = list2env(data))```

and changing the reference here:

https://github.com/stan-dev/cmdstanr/blob/master/R/model.R#L661

I can submit a pull req.

**Comment by cdriveraus** [comment]
just a pointer that you're probably on top of -- many types of objects can be zero dimensional and have a corresponding single or multi dimensional array, which can also be zero dimensional. I just remember stan going through the procedure that some things were fixed for zero dimensions while others were not :)

**Comment by rok-cesnovar** [comment]
@bbbales2 Will have a look, it should definitely be doable. I just need to make a simple example that I can test on.

**Comment by bbbales2** [comment]
I just played with this a little and didn't figure out how to pass in 0x0s with cmdstan:
```
data {
  matrix[0, 0] x;
}

parameters {
  real a;
}

model {
  a ~ normal(0, 1);
}
```

Here's data:

```
data = list(N = 0, x = array(1, dim = c(0, 0)))
write_stan_json(data, "tmp.json")
stan_rdump(names(data), "tmp.dat", env = list2env(data))
```

**Comment by bbbales2** [comment]
It serializes to (Ignore the N):
```
{
  "N": 0,
  "x": []
}
```

The declaration:

```
"x" : [[]]
```

Corresponds to the matrix sized (1, 0)

**Comment by rok-cesnovar** [comment]
Shouldnt this be 
data = list(N = 0, x = array(1, dim = c(**1**, 0)))
write_stan_json(data, "tmp.json")

This produces 
{"N":0,"x":[[]]} 

You can just call 
print(jsonlite::toJSON(data, null = "list", auto_unbox = TRUE))

This is what happens behind the scenes actually.

**Comment by bbbales2** [comment]
Right, but there are models that lean on 0x0, which we can't do right now. So I think it'd work if Charles changed his model but it'd be better if we fixed the problem our side.

**Comment by rok-cesnovar** [comment]
I mean, isn't dim = c(0,0) actually an empty matrix with no rows?

Now that I have thought about it a bit more, we can't make an empty 2D matrix with 0,0 in JSON, because [[]] is considered (1,0) and (0,0) is the same as (0). In R dump you can specify the dimensionality of a structure. In JSON you cant.

If we somehow make it output "[[]]" for this case, cmdstan will read it as (1,0) which again will not work.

So one fix would be to use rdump whenever one uses (0,0) or (0,0,0). Then make our own rdump to not rely on rstan. For now we can switch back to using while I try to make our own rdump function to cover this case.

**Comment by bbbales2** [comment]
I'll make a pull. Yeah I don't know what to do. I think cmdstan should probably just accept a size (0) object for any  multidimensional object where any single dimension is zero. I guess that's sloppy but the other option is trying to modify JSON or not allowing it which both seem less ideal.

**Comment by rok-cesnovar** [comment]
You should probably use it only for a specific case if you find data with dim(0,0) or (0,0,0) or make a `use_rdump` flag, otherwise, you will have to redo all the tests.

If a user tries to use a dim = c(0,0) with default (use_rdump = FALSE) we can stop and say that this is not allowed with JSON and to use use_rdump or rethink the model.

> I think cmdstan should probably just accept a size (0) object for any multidimensional object where any single dimension is zero

+1

I don't think this is too sloppy. cmdstanpy is stuck with this issue if we don't fix it in cmdstan. I imagine this will also be an issue if we try going with binary, etc.

**Comment by mitzimorris** [comment]
>I don't think this is too sloppy. cmdstanpy is stuck with this issue if we don't fix it in cmdstan. I imagine this will also be an issue if we try going with binary, etc.
>
>EDIT: Well, actually accept dim(0) for dim(0,0) and dim(0,0,0). Don't think it would we wise to accept it for dim(3,2,0)

doable, but what a hack!

**Comment by rok-cesnovar** [comment]
Agree that its a hack. 

I am really not sure what would be the best way to proceed here. 

a) tell the users to reformulate their model to not use dim(0,0) and dim(0,0,0)
b) fix in cmdstan with the above hack
c) use rdump if any supplied data is dim(0,0) and dim(0,0,0) (obviously doesnt help cmdstanpy)
d) any other ideas?

**Comment by cdriveraus** [comment]
From a user perspective: breaking previously working things for the sake of not doing something that looks a bit hacky but has no apparent downsides, seems unfavorable. If the worry is unforseen consequences / maintenance etc, then yeah, it needs to be weighed up. I would also argue that it would be a bit of a hack UI wise to say that zero dimensions are ok, just don't have too many of them...

**Comment by bbbales2** [comment]
> Agree that its a hack.

I think maybe I started this by calling it sloppy, my bad. Option b -- but let's just call it a solution instead haha.

**Comment by bob-carpenter** [comment]
> From a user perspective: breaking previously working things for the sake of not doing something that looks a bit hacky but has no apparent downsides, seems unfavorable.

We're trying to reconcile the competing goals of making Stan coherent and not breaking existing behavior, even if it's a bug relative to the doc or intention.   When we have existing behavior that was unintended but in some sense "works", we're in a bind.  Sometimes we just change our intentions, but in some cases, it's really just broken and we want to fix it.

We've been trying to exercise judgement on a case-by-case basis.  Here's an example that I find incoherent and would like to eliminate, but works in some edge cases. All arrays in Stan are rectangular in the spec. But if you make a 5 x 5 array, you can then go in and set each row to be a different size array and wind up with something ragged.  That was a bug in the row assignment function that should've flagged an error.  Then people started leaning on this functionality.  The problem is that none of our built-in algorithms work on ragged structures, incuding I/O, so it's a really dodgy practice that we can't support going forward.  In the end, we'll solve this problem by introducing real ragged array structures and eliminating the old usages.

> I just remember stan going through the procedure that some things were fixed for zero dimensions while others were not :)

If you mean that there are bugs in Stan's matrix library where it should be able to handle 0 x 0 matrices but doesn't, that's right.  I just filed a slew of bug reports on that around upgrading to the new testing framework and they're getting fixed.  If you find new ones, please report.

**Comment by bob-carpenter** [comment]
I misunderstood what was being requested in my last comment, but @mitzimorris and @bbbales2 just tried to explain what they think is doing.

> In my stan model I have a data object like: `matrix[ntipred ? nsubjects : 0, ntipred ? ntipred : 0] tipredsdata;`

It would help if you actually shared the use of `tipsredsdata` in your model.  In the usual regression case, we'd have a data declaration `matrix[N, K] x` for a data matrix `x` with `N` entries, each of which is a `K`-vector.  Then we'd have a coefficient vector `vector[K] beta` and there'd be an expression `x * beta` somewhere in the regression.  That makes sense because `x` is `N x K` and `beta` is `K x 1`, so the product is an `N x 1` vector.  If there is no data, then `x` should be `0 x K`, not `0 x 0`.

I understand from @bbbales2 and @mitzimorris that whatever JSON encoding we're using for Stan data is incomplete in that there is no way to provide a `0 x K` input matrix.  Is this also a problem in the R dump format?

Stan itself is limited in the expressions it can provide for matrices.  I don't think we can have a `0 x K` literal in Stan.  I'm opening an issue there because we should be able to have an empty row vector or vector as `[]` and `[]'` respectively.

**Comment by rok-cesnovar** [comment]
The problem is that you cant specify a 0xK or 0xKxN matrix in JSON, regardless of parser. You can do it in Rdump because you can supply the dim() parameter. 

In JSON [[]] is a 1x0 matrix and [] is a 0-sized array. In rdump you can supply an empty list and declare that its a 0x0 matrix with the dim parameter.

**Comment by cdriveraus** [comment]
Bob -- I have a range of cases that cause this sort of problem, mostly done to allow the same compiled model to be used for a range of cases. I don't think the individual cases are very interesting, I could probably work around each case -- that wasn't the point here, I was just reporting a bug, in the sense of behavior allowed by stan and rstan but not allowed by cmdstanr...

**Comment by bob-carpenter** [comment]
Thanks for reporting.  We'll set up a suite of test cases that hopefully covers the situations you've encountered and then document the fixes on the I/O front.
