### ISSUE TITLE
Silent numeric to integer conversion

### ISSUE THREAD

**Issue by jfsalzmann** [stan-dev/cmdstanr#991]
**Describe the bug**
Related to [this thread](https://discourse.mc-stan.org/t/silent-integer-conversion-in-cmdstanr/35402) in the Stan forum:

I noticed that when I specify model with a data variable of type `int` and passing a `numeric` type variable from R with non-zero decimals, that it gets silently converted to integers without showing any warning or error message. That way, I may not notice that Stan internally works with integer converted data.

**To Reproduce**
Run any model with `int` typed data variable, and pass a `numeric` typed variable in R.

**Expected behavior**
Error message and stop (preferred) or at least a warning.

**Operating system**
Windows 11 (22631)

**CmdStanR version number**
cmdstanr 0.7.1

**Additional context**
R 4.3.2 (2023-10-31 ucrt)

**Comment by jsocolar** [comment]
I agree this looks problematic. I think the culprit is [here](https://github.com/stan-dev/cmdstanr/blob/02259ef7aa2a8b1c8de2fa3fc42a9feafd789288/R/data.R#L189)

I’m not too troubled that it silently coerces reals to integers, but it seems really problematic to do so by rounding down, which can be very dangerous if combined with floating point operations.

**Comment by jfsalzmann** [comment]
Thanks for the quick reaction & fix @jsocolar & @andrjohns!
